name: golang-pipeline
on: 
  push:
    tags:
      - 'v*'  # Запуск при пуше тегов, начинающихся с 'v'
    branches:
      - '**'  # Trigger on all branches for push events
  pull_request:
    branches:
      - '**'  # Запуск на всех ветках при pull request
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4

      - name: Run Go Unit Tests
        run: GOOS=linux GOARCH=amd64 go test -v ./...

      - name: Vet
        run: |
          go vet ./...
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ilexsor/docker-final

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }} 
